### PR TITLE
Added footer

### PR DESCRIPTION
**Pull request by koji**
Added footer to pressKit.js, presskit_styles.css and press.html

### CODE REVIEW

**Comment by juniorxsound** [comment]
Thanks! This is great, can we make the ```presskit.js``` part of the footer link to the GitHub repo? 🙌🏻

**Comment by sleepy-maker** [comment]
Added <a>tag to <footer>.

**Comment by koji** [comment]
put a-tag into footer-tag

**Comment by juniorxsound** [comment]
Nice, merging it in. Thanks @sleepy-maker

**Pull request merged**
